<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" href="/css/bloke.css">
        <title>Bloke Application<?php echo $title ?: ''; ?></title>
    </head>
    <body>
        <div id="main" class="pure-g">
            <div class="pure-u-1">
                <?php echo $content; ?>
            </div>
        </div>
    </body>
</html>
